assetPipelineVersion=4.4.0
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx2g -Xms2g -Dfile.encoding=UTF-8
groovyVersion=3.0.9
spockVersion=2.3-groovy-3.0
slf4jVersion=1.7.26
morpheusPluginApiVersion=1.4.2
morpheusMinApplianceVersion=9.0.0
version=1.1.2
